### ISSUE TITLE
Build.yml guide

### ISSUE THREAD

**Issue by heyheysay** [rhomobile/rhomobile-docs#206]
The build.yml guide looks to be missing some information on what systems can be represented in this file.

http://docs.rhomobile.com/en/4.1.0/guide/build_config

Currently shows OS's iphone, wp, symbian, and android in the sample and further down it also shows wm.

But when I build a new project with 4.1 I see iphone, wp8, android and wm.

Would it be possible to have a section in this document for all possible OS's that can be represented in the build.yml file that are build possibilities?  
Also what are all of the options for these OS's?

Below are possible build OS options listed with "rake -T"
android, bb, iphone, win32, winxpe, wince, wm, symbian, & wp8

This section should also list all available Extensions possibilities.  Would be nice if there was a matrix that showed what extension includes what API's.

**Comment by cfh463** [comment]
Closing - this doc has had many updates sinc this issue was filed.
