### ISSUE TITLE
Doc Issue:Rhomobile | Build for Windows

### ISSUE THREAD

**Issue by dhummel** [rhomobile/rhomobile-docs#235]
Bad Link: http://docs.rhomobile.com/en/5.0.0/guide/build_win#build-qt5-for-vs2008 came from: http://docs.rhomobile.com/en/5.0.0/guide/nativesdksetup

There seems to be little to no reference in this docs page about building qt5 libraries for vs2008.  Unless I'm missing it completely.

**Comment by cfh463** [comment]
This seems to have been resolved:

http://docs.rhomobile.com/en/4.1.0/guide/build_win#setup-qt-build-environment
