### ISSUE TITLE
API Log level documentation is misleading for Ruby

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#237]
This is not correct when using Ruby. It should be e.g. `Rho::Log::LEVEL_TRACE`

The reader should not have to interpret Javascript/Ruby conventions. If you really want to leave it to the reader to interpret, you should use the Ruby syntax, not the Javascript syntax. From the JS syntax, there is no way to know in any particular case whether you are referring to a class or to a module.

This is probably a problem through the documentation.

Edit: I do see now it says (For Ruby use "::" instead of "."). It was not clear to me that both dots should be replaced with double colons. I had to look at the source code. In most cases, (e.g. when referencing a method) the second dot should remain, and only the first dot become a colon.

Edit: what is missing here is an `Access` tab. The `Access` tab appears only inconsistently in the API documentation.

Constant: Rho.Log.LEVEL_TRACE (For Ruby use "::" instead of ".")
String: 0
Everything will be logged. Also see settings for controlling log size.

Constant: Rho.Log.LEVEL_INFO (For Ruby use "::" instead of ".")
String: 1
Information level logs and above will be shown.

Constant: Rho.Log.LEVEL_WARNING (For Ruby use "::" instead of ".")
String: 2
Warnings and above will only be shown.

Constant: Rho.Log.LEVEL_ERROR (For Ruby use "::" instead of ".")
String: 3
Error level log messages and above will be shown.

Constant: Rho.Log.LEVEL_FATAL (For Ruby use "::" instead of ".")
String: 4

**Comment by michaelToews** [comment]
I have changed the string in the Values tab to be "(For Ruby use "::" for all "." when referencing constants)" to specify that all dots must be replaced with a double colon since this will always be the case.
