### ISSUE TITLE
Log API - netTrace description is inaccurate

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#239]
> Turn on local http server traces. Traces contain information about connection process, sent and received headers and data. Please note that this parameter will not take an effect in case of remote server app (and / or shared runtime). Default value can be overridden by the setting in rhoconfig.txt (net_trace)

This does not seem to be true.

What does "local http server traces" mean? I'd interpret that as meaning "requests/responses from the internal web server". That doesn't seem to be the case at all.

Tracing of local http server seems to occur only if you set `Log.level` to 0 (trace).

Tracing of `Network::` requests (to external sites) occurs if you set `Log.netTrace` to true, regardless of `Log.level` value. (e.g. I set `Log.level` to `LEVEL_INFO` and still get network tracing.

**Comment by michaelToews** [comment]
Looks like this was fixed a while back in this commit: https://github.com/rhomobile/rhodes/commit/5259e9421348afb3d60cd91ad19ff2bb3c5cc6d7
