### ISSUE TITLE
Doc Issue:Rhomobile | Barcode

### ISSUE THREAD

**Issue by davidmiller66** [rhomobile/rhomobile-docs#278]
http://docs.rhomobile.com/en/5.0.0/api/barcode#

The 'Licencing' section states the following:

"You can fully use all features of this API during evaluation, development or testing without obtaining a license. A message will be displayed on application startup and will also display a nag screen periodically. Before deploying an application to a production environment, you must obtain a license key. Read more about licensing." 

I do not believe this statement to be true for V5+

**Comment by davidmiller66** [comment]
Hi Michael


I don’t think you are right that you can build an app utilising ‘Barcode' without a licence using V5….


Starting rhodes build system using ruby version: 1.9.3

Connecting to https://app.rhohub.com

Connecting to https://appstaging.rhohub.com

 **** ERROR: Could not build licensed features. ***************************************************************

   You have free subscription on https://app.rhohub.com. RhoElements features are available only for paid accounts.

   The following features are only available in RhoElements v2 and above:

   - Barcode extension

   For more information go to http://www.motorolasolutions.com/rhoelements

   In order to upgrade your account please log in to https://app.rhohub.com

   Select "change plan" menu item in your profile settings.

 **************************************************************************************************************

RET: 1



Kind regards



David Miller

**Comment by mmalinin** [comment]
Barcode scanner is still a licensed feature and it could be build only using a paid subscriptions.

**Comment by davidmiller66** [comment]
I suggest then that my original assertion that the documentation is wrong, still stands.  So the original ticket should be re-opened and the documentation corrected.

view it on GitHub<https://github.com/rhomobile/rhomobile-docs/issues/278#issuecomment-69317259>.

**Comment by michaelToews** [comment]
Yes, you are completely correct. I failed to realize that my account on rhohub is a gold level account and I did not downgrade to do this test. I have reopened the issue and I will correct it in the docs.

Sorry about the mixup, totally my mistake.

**Comment by michaelToews** [comment]
This has been fixed in this commit:
https://github.com/rhomobile/rhomobile-docs/commit/aca3ec65cb730a124764d1afe5213a645a8ced8e
