### ISSUE TITLE
iPhone splash screen file list needs updating

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#279]
http://docs.rhomobile.com/en/edge/guide/app_icon_splash

Missing at least:

- loading-Landscape@2x.png
- loading-Portrait@2x.png

These were introduced in 5.0.25

**Comment by michaelToews** [comment]
@rognar Could you please chime in on this? I need some details on these files to add to the docs.

**Comment by michaelToews** [comment]
@rognar Ping.

**Comment by dmitrys** [comment]
This is a complete list of all supported "loading" images on iOS platform :

loading.png 
loading@2x.png 
loading-Portrait.png 
loading-Portrait@2x.png 
loading-PortraitUpsideDown.png 
loading-PortraitUpsideDown@2x.png 
loading-Landscape.png 
loading-Landscape@2x.png 
loading-LandscapeLeft.png 
loading-LandscapeLeft@2x.png 
loading-LandscapeRight.png 
loading-LandscapeRight@2x.png 
loading-568h@2x.png 
loading-667h@2x.png 
loading-736h@3x.png

**Comment by michaelToews** [comment]
Dmitry, thank you very much for this list. This is very useful. Can you also provide some descriptions of when these different images would be used? I can infer from the other entries in the docs for some of them but, don't want to guess incorrectly.

**Comment by dmitrys** [comment]
loading.png - size 320x480 – for iPhone/iPod/iPad and other non iOS devices
loading@2x.png - size 640x960 – for from iPhone4/iPod4/Iphone4S (retina)
loading-Portrait.png - size 768x1024 – for iPad in Portrait orientation
loading-Portrait@2x.png - size 1536x2048 - for iPad retina in Portrait orientation
loading-PortraitUpsideDown.png - size 768x1024 – for iPad in Portrait Upside Down orientation  
loading-PortraitUpsideDown@2x.png - size 1536x2048 – for iPad retina in Portrait Upside Down orientation 
loading-Landscape.png - size 1024x768 – for iPad in Landscape orientation 
loading-Landscape@2x.png - size 2048x1536 – for iPad retina in Landscape orientation 
loading-LandscapeLeft.png - size 1024x768 – for iPad in Landscape Left orientation 
loading-LandscapeLeft@2x.png - size 2048x1536 – for iPad retina in Landscape Left orientation 
loading-LandscapeRight.png - size 1024x768 – for iPad in Landscape Right orientation 
loading-LandscapeRight@2x.png - size 2048x1536 – for iPad retina in Landscape Right orientation 
loading-568h@2x.png - size 640x1136 - for iPhone5/5S/5C
loading-667h@2x.png - size 750x1334 - for iPhone6
loading-736h@3x.png - size 1242x2208 - for iPhone6Plus

**Comment by michaelToews** [comment]
Dmitry, thanks for that info.

I have added the info here but issues the wrong issue number to the commit.
GH Commit: https://github.com/rhomobile/rhomobile-docs/commit/54db3b320f8ab6a517d091ddc9a86fdc29e0c617

**Comment by jtara** [comment]
I think it's worth noting that the lack of certain of these images will trigger iOS to assume that the app was not designed to work with certain device, and then the app will run in a kind of "letterbox" mode.

For example, if the 568h image is missing, the when the app is run on an iPhone 5/5S, the app will have black bars at the top and bottom.

I believe the same is true for iPhone 6/6+.

Finally, there seems to be (or have been, haven't tested lately) a bug with Rhodes where you must supply the upside-down images, or else you will get the default RhoMobile image. Well, here, I'm not sure just what the intent is.

It would seem reasonable to me that if the developer does not supply the upside-down, then Rhodes build ought to copy the rightside-up image to the bundle as the upside-down as well.

In practice, then, I find it's important to supply every one of these images. Upside down's and landscape left/right images can just be identical, unless you actually WANT the image upside-down, (or alternative image).

I think I have an Issue on this in Rhomobile/Rhodes. I'll link it from here.

So, I'm going to re-open this so that it might get a big more attention yet. ;) I appreciate all of the diligence on the docs, though!

Hmmm... no, I don't have an Issue on Rhodes about that. Since I am working on a brand-new project, I will have an opportunity to check that out with current build of SP3, and I will open an Issue if there is still a problem with missing upside-downs and landscape-rights. 

IMO, it ought to allow you to omit them, and not get the default RhoMobile splashes. Or, if not, it should be documented. I'll add something on that in the next couple of days.

**Comment by jtara** [comment]
Oh. I don't think there are any "behind the scenes" splash images that are provided by Rhodes if you do not supply them!

When you generate a project, you get them in your generated project. So, it will depend on the version of Rhodes that you used to generate it. If Apple comes out with a new product with a new screen size, and you've updated your Rhodes Gem, now you have to update your splash images yourself too.

Since the upside-down images and left/right images are generated for you, now it's up to you to replace both with your own, or (duh) you get the ones that were generated in your project.

For reference, this is what I have in a project recently-generated by Rhodes SP3 (unreleased). I haven't changed any splash images yet!

![splashes](https://cloud.githubusercontent.com/assets/958610/6476530/f3693054-c1cb-11e4-8327-6e04b05c61b7.png)
