### ISSUE TITLE
Doc Issue:Rhomobile | Remote Build Guide

### ISSUE THREAD

**Issue by redlandmover** [rhomobile/rhomobile-docs#280]
Need to update "Setting Up Your Remote Repo"/"Online Interface"/"Git Integration" sections.

Site documentation can be found in the app->more info section and profile->github section.

**Comment by michaelToews** [comment]
Added private GH repo instructions, please take a look [here](https://github.com/rhomobile/rhomobile-docs/blob/4bacd42b770a462f6e4f5c4aafdc6395dbaf4a6a/docs/en/hosted/guide/remote-build-guide.md) and close this issue if it looks good.

Keep in mind that the formatting on GH is not exactly what it will look like on the live site but it is a close representation.

**Comment by redlandmover** [comment]
looks good.
