### ISSUE TITLE
Unimplemented 5.x Camera API docs should be removed

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#282]
The API documentation includes documentation for the unimplemented 5.x Camera API. Unless I am missing something, currently (5.0.25) only the only 2.2-style Camera API is present in Rhodes.

I think there was intent to release a new Camera API with 5.x, but it has not be done yet. The documentation apparently was already written, and is present on the documentation site, though.

The link in the list of APIs does take you (correctly) to the 2.2 documentation. However, the 5.x documentation page exists, and users are able to navigate to to manually, by forming the URL in the browser navigation bar - and apparently have. See below:

https://developer.motorolasolutions.com/message/82936#82936

I don't know if there might also be some stray link or links elsewhere in the documentation that may lead to this page.

Here is a link to the documentation page I am referring to. It's my understanding that this is currently not implemented in Rhodes. It is about the (apparently unimplemented) `mediacapture` API.

http://docs.rhomobile.com/en/5.0.25/api/camera

It would be best if documentation pages for not-implemented features that are waiting for some future release are not included in the documentation at all. Archive them somewhere out of public view for future use. Otherwise, Rhodes developers will be confused by it.

**Comment by michaelToews** [comment]
Thanks for the input, Jon. I completely agree and I have added a tag into the Camera API code that will keep it from regenerating. I'll make sure to add this to the other un-implemented APIs.
