### ISSUE TITLE
Doc Issue:Rhomobile | Not Found

### ISSUE THREAD

**Issue by vmusulainen** [rhomobile/rhomobile-docs#284]
Bad Link: http://docs.rhomobile.com/en/5.0.25/api/camera came from: http://docs.rhomobile.com/search?q=torch

**Comment by michaelToews** [comment]
Yes, the Camera common API does not exist yet, we just need to clean up the search index to make sure it does not include those pages.

**Comment by michaelToews** [comment]
The search should be fixed at this point. A search for camera only results in finding the camera guide.
