### ISSUE TITLE
ERB templates are only barely documented for 4.x/5.x

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#287]
Use of templates, especially advanced use is now only barely documented in the 4.x/5.x documentation. 

I can only find this scarce documentation:

http://docs.rhomobile.com/en/5.0.25/guide/uichoices

It doesn't mention partials or collections at all!

Maybe I am looking in the wrong place?

So, only those who have been using Rhodes for a while know how to use these features. The old documentation is still there, but most will not know where to find it. e.g.:

http://docs.rhomobile.com/en/2.2.0/rhodes/ui

Can this documentation (updated, if needed) please be brought into the 5.x documentation set? Or, if it actually exists there, perhaps some attention should be given to linking it from some place where it will be easily found?

**Comment by michaelToews** [comment]
As I understood it, partials were not supported in Rhodes; were you able to get them to work?

**Comment by jtara** [comment]
I couldn't live without them!

Yes, I use them extensively. Every. Little. Thing.

I had to refresh my memory for a new project, that's why the documentation came up.

Simple example:

Songs/index.erb

``` erb
<div data-role='page'>
	<div data-role='header' data-id='1'>
    <h1>Songs</h1>
    <a href='<%= Rho::Application.startURI %>' class='ui-btn-left ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-home' data-direction='reverse'>
      Home
    </a>
	</div>
  <div role='main' class='ui-content'>
    <%= render :partial => 'song_list', :locals => { :songs => @songs } %>
  </div>
</div>
```

Songs/_song_list.erb

``` erb
<ul data-role='listview'>
  <%= render :partial => 'song', :collection => @songs %>
</ul>
```

Songs/_song.erb

``` erb
<li data-object='<%= song.object %>'>
  <p><%= song.title %></p>
  <p><%= song.artist %></p>
  <p><%= song.album %></p>
  <p><%= song.duration %></p>
</li>
```

Tremendously convenient, and should be encouraged. But it won't be used if the documentation is lost!

**Comment by michaelToews** [comment]
Oh, thank you very much. I may be remembering a conversation with a former employee long ago. It's great to know that partials work so well in RhoMobile. And yes, I agree, documentation for this is necessary.

**Comment by jtara** [comment]
I seem to recall that in very ancient history, there might have been some problem with calling partials from partials. You can see from my example above, though, that that's certainly not the case now.

I think some developers shy-away from partials because they have the mistaken impression that they are inefficient. You might easily imagine a file being read and parsed every time you use a partial.

What really happens:

- At build time, the partial is transformed from ERB to Ruby code
- Then (still at build time) the Ruby code is compiled to Ruby bytecode
- At run time, a file of Ruby bytecode is read into memory upon first encounter. Then it stays there (in memory)
- Other than that initial load, the overhead of using a partial is the overhead of a Ruby call and return. In other words, insignifigant.

It would be worth pointing-out how efficient this is.

I tend to use very tiny, atomic partials. I usually go beyond what is shown above, and make partials even for individual parts of a list item, for example.

You should still use CSS to alter appearance. But if you DO get sloppy and use inline styles, etc. it is much more manageable with partials. And now you have the freedom to alter structure, add a CSS class you thought you wouldn't need, etc. etc. much more easily than with some massive editor search-and-replace.

So, it's well worth bringing this documentation up-to-date and into the 5.x docs.

**Comment by michaelToews** [comment]
I'm adding what we have in our 2.2 docs in the Advanced Use of Render section into the uichoices doc that you mentioned in the original comment. We will probably need to update the content but I don't think it has really changed since it was implemented.

That having been said, may I use what you have here in your latest comment as source for some updated content in the docs?

**Comment by jtara** [comment]
Sure, feel free to use anything I've posted here.

I'd imagine it is unlikely anything about this is going to change any time soon. It uses a rather unique implementation of ERB called Templater. Here is the GitHub project for it:

https://github.com/jnicklas/templater

It's stuck at version 1.0, and probably always will be. But that I think is mainly because it's an oldie-but-goodie. It does the limited things that it does well. Let's just say that it is "mature" - with everything that goes with that, and that's not a bad thing. 

I don't know how much modification and adaptation has been done, but you will notice that the Templater 1.0 Gem is fetched and loaded when you install the Rhodes Gem.

It's quite a bit different from ERB as typically implemented in Rails, Sinatra, etc. There is a build-time part, and a run-time library. At build time (when you run `rake:run` or `rake:device`) it converts the ERB to Ruby code. That Ruby code makes calls to a some runtime functions that must be implemented. (And have been in Rhodes.). 

Rhodes then goes on (at build time) to compile the Ruby code to Ruby bytecode. 

So, at run-time, Ruby bytecode is loaded, and that Ruby bytecode calls the runtime functions that fill-in the variable parts, run Ruby code supplied in `<% %>` blocks, etc.

It's rather clever, and not at all what it might seem on the surface!

I've had some talks with the author of Slim Templates about the possibility of making them work in Rhodes. Because Slim now has capability for separate run-time and build-time similar to Templater, it remains an intriguing possibility, but not something I have the time to do right now. I really, really like Slim Templates, but they are not everybody's cup of tea.

**Comment by michaelToews** [comment]
Jon, thank you very much for your insights on this. I find this kind of description incredibly helpful and I feel our developer community would as well.
