### ISSUE TITLE
Doc Issue:Rhomobile | Battery

### ISSUE THREAD

**Issue by pfmaggi** [rhomobile/rhomobile-docs#288]
Licensing note at the end of this document is wrong.

BTW the document states that this API provide a way to display a battery icon only on WinCE/WM devices, in reality even Android is supported (or at least the ShowIcon method is listed as supporting Android). I used to display the battery icon on MC40 JB a couple of version ago. So, it was working, never tested this latest version.

Bad Link: http://docs.rhomobile.com/en/5.0.25/api/battery came from: http://docs.rhomobile.com/en/5.0.25/api/Intent

**Comment by michaelToews** [comment]
Could you elaborate on how the license section is wrong?

**Comment by pfmaggi** [comment]
The License section describe the "per-device" license, not the new Subscription model introduced in v5.0.

**Comment by michaelToews** [comment]
Right! Thank you. I'll get on fixing that right away.

**Comment by michaelToews** [comment]
This is the licensing section from that page. Am I missing something in there about device licenses?

>You can fully use all features of this API during evaluation, development or testing without obtaining a license. A message will be displayed on application startup and will also display a nag screen periodically. Before deploying an application to a production environment, you must obtain a license key. Read more about licensing.
>

**Comment by pfmaggi** [comment]
That paragraph describe the behaviour of the device license (pre-RMSv5.0).
This is a documentation page for RMS v5.0.25. Would be fine if you use this paragraph for Enterprise Browser docs, but not here, not for RMS5 that has a subscription license model.


In the new subscription model there's no evaluation phase: you need to have a subscription to **compile** an application.
Can be a free subscription if you're not using RhoElements features or a trial/payd subscription for RhoElements features and cloud builds.
You can refer to the [RhoMobile pricing page](http://rhomobile.com/pricing/).

**Comment by michaelToews** [comment]
Yes, you're right. Sorry, I completely blanked on all that for a sec. I'll fix this licensing section today.
