### ISSUE TITLE
Doc Issue:Rhomobile | Wake Module

### ISSUE THREAD

**Issue by vmusulainen** [rhomobile/rhomobile-docs#291]
Bad Link: http://docs.rhomobile.com/en/2.2.0/rhoelements/wake came from: http://docs.rhomobile.com/en/5.0.25/home

**Comment by michaelToews** [comment]
@vmusulainen Can you explain the steps you took to get this bad link?

**Comment by vmusulainen** [comment]
Yes, sure

docs.rhomobile.com <http://docs.rhomobile.com/> -> API Reference link -> Wake Module -> http://docs.rhomobile.com/en/2.2.0/rhoelements/wake <http://docs.rhomobile.com/en/2.2.0/rhoelements/wake>

**Comment by michaelToews** [comment]
This link is working as intended. This must link to 2.2.0 docs as there is no common API for the Wake module.

**Comment by vmusulainen** [comment]
it is absolutely not clear.

I saw customer reaction when he opened doc version 5.0.25, saw Wake module in list api and clicked on it and op-s-s. It's 2.2..

The first reaction was: ‘You provide access via Common API to Wake module in 5.0.25!’.
The second reaction: “Hm, It’s 2.2 API. Hm, Wrong link? Do you support Wake module in 5.0.25?”

regards
Vladimir Musulainen

**Comment by michaelToews** [comment]
Are you suggesting that we separate the Common APIs from the non-common APIs? If you have a suggestion on a better way to do this, I am open for suggestions.

**Comment by vmusulainen** [comment]
May be set label/badge for non-common API modules?

regards
Vladimir Musulainen

**Comment by michaelToews** [comment]
We currently have an asterisk (*) next to all non-common APIs in the list. Was that not clear? It is possible that it was not clear enough with just that.

Are you thinking more of a label like "Legacy API" or something?

**Comment by darryncampbell** [comment]
It's a really difficult thing to communicate, I agree it's confusing but I'm not sure how best to address it... we used to maintain a separate list BUT it was Adam who requested that we present an amalgamated list to developers.  Unfortunately, I don't see this confusion going away until we properly implement the common API.
