### ISSUE TITLE
Doc Issue:Rhomobile | Home

### ISSUE THREAD

**Issue by jonboriotti** [rhomobile/rhomobile-docs#294]
Bad Link: http://docs.rhomobile.com/en/5.0.25/home came from: http://docs.rhomobile.com/en/5.0.25/guide/apisummary#

Search function appears busted. Can't search on any terms.

**Comment by michaelToews** [comment]
Yes, this was due to an unauthorized token issue. It should be resolved now and will be functional again by tomorrow at the latest.
