### ISSUE TITLE
Doc Issue:Rhomobile | Not Found

### ISSUE THREAD

**Issue by raghavendrakc** [rhomobile/rhomobile-docs#296]
Bad Link: http://docs.rhomobile.com/en/edge/api/Camera came from: http://docs.rhomobile.com/en/edge/guide/apisummary

**Comment by abhineetagarwal** [comment]
@raghavendrakc :Will be fixed....

**Comment by raghavendrakc** [comment]
@abhineetagarwal : Today we are sending beta to Via Data. Please find before EOD will be good.
Thanks.

**Comment by abhineetagarwal** [comment]
@raghavendrakc : Sure. Thanks..

**Comment by abhineetagarwal** [comment]
@michaelToews : Hi Michael, I have modified the camera link for the same with the below commit.
https://github.com/rhomobile/rhomobile-docs/commit/b1c9ed9ed16117d87191cb2e51bc160ce43b0a29

Please update the same in http://docs.rhomobile.com.
Thanks.

**Comment by cfh463** [comment]
@abhineetagarwal It will not be updated in docs.rhomobile.com until 5.1 is released. Edge is the correct place for this link at this time.

**Comment by abhineetagarwal** [comment]
@michaelToews: I mean the same too... :)

@raghavendrakc: It is now available in the edge docs...
